### ISSUE TITLE
Active tab visibility is low for monitors with bad contrast

### ISSUE THREAD

**Issue by ryleysevier** [DragWx/vsc-astronomy-theme#13]
Can you submit a bug on a visual design request?

On crappy contrast, the three colors around an active tab make it difficult to see which one is currently selected. 
Maybe a sub theme with a high contrast color to indicate the current active tab?

Solid theme. My default.

**Comment by DragWx** [comment]
Yeah, I ran into that issue too, the latest update adds a top bar to the active tab for that reason, but I can see about other ways to improve contrast between the tabs.

**Comment by DragWx** [comment]
![image](https://user-images.githubusercontent.com/1189874/133002314-c78996df-33d7-4f50-9b45-5ca59296e91c.png)
Is this acceptable or is more necessary?

**Comment by ryleysevier** [comment]
Can you show that with breadcrumbs as well?

**Comment by DragWx** [comment]
![image](https://user-images.githubusercontent.com/1189874/133005334-37b76e7f-6c6f-4b5f-bcf0-a95ea0d3f21d.png)
Here it is with breadcrumbs turned on.

**Comment by ryleysevier** [comment]
That's perfect. Matching the active content looks good even at a bad angle on my crappy monitor.

**Comment by DragWx** [comment]
Excellent, I'll publish this update momentarily.
